### ISSUE TITLE
Is there a preferred way to check the value of a Switch?

### ISSUE THREAD

**Issue by catastrophe-brandon** [RedHatQE/widgetastic.patternfly5#42]
As I understand it, the Switch widget does not currently implement `read()`:

```
>       raise DoNotReadThisWidget(f"Widget {type(self).__name__} does not implement read()")
E       widgetastic.exceptions.DoNotReadThisWidget: Widget Switch does not implement read()
```

Is there a recommended way to check the value of a Switch? I would like to do the following:

1. Check the value of Switch
2. Perform an action depending on whether the switch is ON or OFF

At present, it appears that I can only click on a switch widget.

**Comment by mshriver** [comment]
@catastrophe-brandon I hadn't seen this! Mayuri Hadole is currently working on something for this in iqe-content-sources, which we can absolutely bring to wt.PF5.

The aria-labelledby attribute needs to be checked
